### ISSUE TITLE
Tree visualization 

### ISSUE THREAD

**Issue by tomarashish** [ProteinsWebTeam/genome-properties-viewer#1]
Hi @4ndr01d3,

I am working on tree visualization for my Ph.D. project. I would like to contribute to this project and try out different visualization layout with genome properties data. My idea is to use an indented layout/sunburst for browsing the hierarchy. We can discuss more if you like the idea.

**Comment by 4ndr01d3** [comment]
Hey @tomarashish ,
Good to hear of your interest in the project. 
And yeah, always happy to listen to other ideas, so if you are interested in implementing a prototype of your idea, just fork the project and let us know when you have some demo.
BTW, We have another repo(https://github.com/ebi-pf-team/genome-properties/) where we are maintaining the genome properties data, so you can use that when testing your project. 
Also, if you haven't seen it, the website of the project is here: https://www.ebi.ac.uk/interpro/genomeproperties/
